### ISSUE TITLE
Register with the homebrew-nodenv tap

### ISSUE THREAD

**Issue by hurrymaplelad** [hurrymaplelad/nodenv-package-json-engine#1]
So that we can install via homebrew.

https://github.com/jawshooah/homebrew-nodenv

**Comment by hurrymaplelad** [comment]
Pending https://github.com/jawshooah/homebrew-nodenv/pull/6

**Comment by jasonkarns** [comment]
looks like this is done and can be closed

**Comment by hurrymaplelad** [comment]
Right-o!
